CREATE DATABASE flashcard_db;

USE flashcard_db;

CREATE TABLE CS_flashcards(
	id INT NOT NULL AUTO_INCREMENT,
	CS_questions VARCHAR(255) NOT NULL,
	CS_answers VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE CSS_flashcards(
	id INT NOT NULL AUTO_INCREMENT,
	CSS_questions VARCHAR(255) NOT NULL,
	CSS_answers VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE SQL_flashcards(
	id INT NOT NULL AUTO_INCREMENT,
	SQL_questions VARCHAR(255) NOT NULL,
	SQL_answers VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);